// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT8J9gem6VM_xx9LAJNQ3GO2BywWwFiuU',
    appId: '1:7740304928:web:84d48bb93af74285659645',
    messagingSenderId: '7740304928',
    projectId: 'inventory-app-38ae6',
    authDomain: 'inventory-app-38ae6.firebaseapp.com',
    storageBucket: 'inventory-app-38ae6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANqky1tvDgJQ5h5q28oXUIr4jZ6B6e_wI',
    appId: '1:7740304928:android:a4d765627c5ae334659645',
    messagingSenderId: '7740304928',
    projectId: 'inventory-app-38ae6',
    storageBucket: 'inventory-app-38ae6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV0RqMkcdC1DNQhc--xw9RveTWT_HwyUA',
    appId: '1:7740304928:ios:140e8e7f4136d268659645',
    messagingSenderId: '7740304928',
    projectId: 'inventory-app-38ae6',
    storageBucket: 'inventory-app-38ae6.firebasestorage.app',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV0RqMkcdC1DNQhc--xw9RveTWT_HwyUA',
    appId: '1:7740304928:ios:140e8e7f4136d268659645',
    messagingSenderId: '7740304928',
    projectId: 'inventory-app-38ae6',
    storageBucket: 'inventory-app-38ae6.firebasestorage.app',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT8J9gem6VM_xx9LAJNQ3GO2BywWwFiuU',
    appId: '1:7740304928:web:ed327d8831bcf241659645',
    messagingSenderId: '7740304928',
    projectId: 'inventory-app-38ae6',
    authDomain: 'inventory-app-38ae6.firebaseapp.com',
    storageBucket: 'inventory-app-38ae6.firebasestorage.app',
  );
}
